language: generic

sudo: required
services:
 - docker

before_install:
 - docker build -t konsloiz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true konsloiz/docker-react npm run test